import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart';
import '../models/action_log.dart';

/// Service for logging and retrieving camera action history from Firestore
class ActionLogService {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final FirebaseAuth _auth = FirebaseAuth.instance;

  // Collection reference for action logs
  static CollectionReference get _actionLogsCollection =>
      _firestore.collection('action_logs');

  /// Log an action to Firestore
  static Future<void> logAction({
    required String cameraName,
    required ActionType actionType,
  }) async {
    try {
      final user = _auth.currentUser;
      if (user == null) {
        throw Exception('User not authenticated');
      }

      final actionLog = ActionLog(
        id: '', // Will be auto-generated by Firestore
        timestamp: DateTime.now(),
        cameraName: cameraName,
        userId: user.uid,
        userEmail: user.email ?? '',
        actionType: actionType,
      );

      await _actionLogsCollection.add(actionLog.toMap());
    } catch (e) {
      debugPrint('[ActionLogService] Failed to log action: $e');
    }
  }

  /// Get all action logs for the current user with pagination
  static Future<List<ActionLog>> getUserActionLogsPaginated({
    int limit = 20,
    int offset = 0,
  }) async {
    try {
      final user = _auth.currentUser;
      if (user == null) {
        return [];
      }

      final snapshot = await _actionLogsCollection
          .where('user_id', isEqualTo: user.uid)
          .orderBy('timestamp', descending: true)
          .limit(limit + offset)
          .get();

      final allLogs = snapshot.docs
          .map((doc) => ActionLog.fromDocument(doc))
          .toList();

      // Skip the offset and return the limit
      if (offset >= allLogs.length) {
        return [];
      }

      return allLogs.skip(offset).take(limit).toList();
    } catch (e) {
      debugPrint('[ActionLogService] Failed to fetch action logs: $e');
      return [];
    }
  }

  /// Clear all action logs for the current user
  static Future<void> clearUserActionLogs() async {
    try {
      final user = _auth.currentUser;
      if (user == null) {
        throw Exception('User not authenticated');
      }

      final snapshot = await _actionLogsCollection
          .where('user_id', isEqualTo: user.uid)
          .get();

      final batch = _firestore.batch();
      for (final doc in snapshot.docs) {
        batch.delete(doc.reference);
      }

      await batch.commit();
    } catch (e) {
      throw Exception('Failed to clear action logs: $e');
    }
  }
}
